//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hasan.App.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HasanHoutoneEntities : DbContext
    {
        public HasanHoutoneEntities()
            : base("name=HasanHoutoneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<CompanyForm> CompanyForm { get; set; }
        public virtual DbSet<CompanyModule> CompanyModule { get; set; }
        public virtual DbSet<Forms> Forms { get; set; }
        public virtual DbSet<Modules> Modules { get; set; }
        public virtual DbSet<StaffList> StaffList { get; set; }
        public virtual DbSet<tbl_Drop> tbl_Drop { get; set; }
        public virtual DbSet<tbl_Drug> tbl_Drug { get; set; }
        public virtual DbSet<tbl_Investigation> tbl_Investigation { get; set; }
        public virtual DbSet<tbl_Patient> tbl_Patient { get; set; }
        public virtual DbSet<Usergroup> Usergroup { get; set; }
        public virtual DbSet<UserGroupForm> UserGroupForm { get; set; }
        public virtual DbSet<UserGroupModule> UserGroupModule { get; set; }
    }
}
