//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hasan.App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Patient
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string ChiefComplains { get; set; }
        public Nullable<int> Age { get; set; }
        public string Sex { get; set; }
        public string Mrno { get; set; }
    }
}
