//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hasan.App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Rx
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Rx()
        {
            this.tbl_RxDrop = new HashSet<tbl_RxDrop>();
            this.tbl_RxDrug = new HashSet<tbl_RxDrug>();
            this.tbl_RxInvestigation = new HashSet<tbl_RxInvestigation>();
        }
    
        public int Id { get; set; }
        public Nullable<int> MajorAreaId { get; set; }
        public string Rx { get; set; }
        public Nullable<int> PatientId { get; set; }
        public string NextVisit { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    
        public virtual tbl_MajorArea tbl_MajorArea { get; set; }
        public virtual tbl_Patient tbl_Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RxDrop> tbl_RxDrop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RxDrug> tbl_RxDrug { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RxInvestigation> tbl_RxInvestigation { get; set; }
    }
}
