//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hasan.App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RxInvestigation
    {
        public int Id { get; set; }
        public Nullable<int> RxId { get; set; }
        public Nullable<int> InvestigationId { get; set; }
        public string Instruction { get; set; }
    
        public virtual tbl_Investigation tbl_Investigation { get; set; }
        public virtual tbl_Rx tbl_Rx { get; set; }
    }
}
