//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hasan.App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Rx
    {
        public int Id { get; set; }
        public Nullable<int> MajorAreaId { get; set; }
        public string Rx { get; set; }
        public Nullable<int> PatientId { get; set; }
        public string NextVisit { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    
        public virtual tbl_MajorArea tbl_MajorArea { get; set; }
        public virtual tbl_Patient tbl_Patient { get; set; }
    }
}
